[package]
name = "yass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-regex = "2.3.0"
clap = { version = "3.1.18", features = ["derive"] }

